## Final Project

**Task 1 (Business Understanding)**
* Jelaskan tujuan bisnis: Mengidentifikasi pola transaksi penipuan untuk mengurangi kerugian finansial dan meningkatkan keamanan platform "PayNow"
* Definisikan masalah: Adanya peningkatan transaksi fraud yang belum teridentifikasi polanya secara jelas.
* Rumuskan pertanyaan-pertanyaan kunci untuk analisis: Apa saja karakteristik umum dari transaksi fraud? Apakah ada pola waktu (jam/hari) tertentu? Bagaimana perbandingan nilai transaksi antara fraud dan non-fraud?

**Jawaban 1**

**Task 2 (Data Understanding:)**
* Muat dataset transaksi yang disediakan.
* Lakukan investigasi awal: tampilkan informasi dasar (.info(), .shape), beberapa baris data (.head()), dan statistik deskriptif (.describe()).
* Berikan interpretasi singkat dari statistik deskriptif. Fokus pada kolom kunci seperti transaction_amount dan is_fraud (jika ada). Apa yang bisa Anda simpulkan dari nilai rata-rata, standar deviasi, min, dan max?

**Jawaban 2**

berdasarkan rata-rata yang diperoleh nilai 0.230303 yang dan jika di persentasekan sekitar 23% dari total 330 transaksi tersebut adalah penipuan (fraud). Sisanya, sekitar 77%, adalah transaksi normal.Mayoritas Data adalah Normal: Karena nilai pada kuartil 25%, 50%, dan 75% semuanya adalah 0, ini mengonfirmasi bahwa mayoritas transaksi di datasetmu (setidaknya tiga perempatnya) adalah transaksi normal yang aman. Angka 1 (fraud) baru muncul di 25% data teratas.

In [ ]:
import pandas as pd
df_DataSet = pd.read_csv('transactions_fraud_detection.csv')
df_DisplayDataSet= pd.DataFrame(df_DataSet)
display(df_DisplayDataSet)
print('Head Data')
display(df_DisplayDataSet.head())
print('Info data')
display(df_DisplayDataSet.info())
print('Shape Data')
display(df_DisplayDataSet.shape)
print('Describe Data')
display(df_DisplayDataSet.describe())
ringkasan = df_DisplayDataSet['is_fraud'].describe()
nilai_mean_fraud = ringkasan['mean'] #ambil nilai spesifik dari describe 
persentase = round(nilai_mean_fraud*100,2)
print('Nilai Mean = ',nilai_mean_fraud)
print('Persentase = ',persentase, '%')

,transaction_id,user_id,transaction_time,transaction_amount,payment_method,device_id,ip_address,billing_country,is_fraud
0,TXN0001,USER043,2024-01-01 00:05:32,150.75,credit card,DEV076,192.168.1.1,USA,0.0
1,TXN0002,USER012,2024-01-01 01:15:45,25.50,paypal,DEV033,10.0.0.5,US,0.0
2,TXN0003,USER089,2024-01-01 02:30:10,$5000.00,gift card,DEV101,172.16.0.8,RU,1.0
3,TXN0004,USER043,2024-01-01 03:45:22,75.20,Credit Card,DEV076,192.168.1.1,USA,0.0
4,TXN0005,USER012,2024-01-01 04:55:30,120.00,debit card,NaN,10.0.0.5,US,0.0
...,...,...,...,...,...,...,...,...,...
326,TXN0324,USER197,2024-01-14 12:10:00,765.00,debit card,DEV216,9.0.1.3,USA,0.0
327,TXN0325,USER198,2024-01-14 13:20:00,775.00,credit card,DEV217,0.1.2.4,USA,0.0
328,TXN0326,USER203,2024-01-14 14:30:00,1.65,credit card,DEV222,12.13.14.15,VN,1.0
329,TXN0327,USER199,2024-01-14 15:40:00,785.00,paypal,DEV218,1.2.3.5,USA,0.0
330,TXN0328,USER200,2024-01-14 16:50:00,795.00,debit card,DEV219,2.3.4.6,USA,0.0

Head Data

,transaction_id,user_id,transaction_time,transaction_amount,payment_method,device_id,ip_address,billing_country,is_fraud
0,TXN0001,USER043,2024-01-01 00:05:32,150.75,credit card,DEV076,192.168.1.1,USA,0.0
1,TXN0002,USER012,2024-01-01 01:15:45,25.50,paypal,DEV033,10.0.0.5,US,0.0
2,TXN0003,USER089,2024-01-01 02:30:10,$5000.00,gift card,DEV101,172.16.0.8,RU,1.0
3,TXN0004,USER043,2024-01-01 03:45:22,75.20,Credit Card,DEV076,192.168.1.1,USA,0.0
4,TXN0005,USER012,2024-01-01 04:55:30,120.00,debit card,NaN,10.0.0.5,US,0.0

Info data
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 331 entries, 0 to 330
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   transaction_id      331 non-null    object
 1   user_id             331 non-null    object
 2   transaction_time    331 non-null    object
 3   transaction_amount  330 non-null    object
 4   payment_method      331 non-null    object
 5   device_id           329 non-null    object
 6   ip_address          328 non-null    object
 7   billing_country     330 non-null    object
 8   is_fraud            330 non-null    float64
dtypes: float64(1), object(8)
memory usage: 23.4+ KB

None

Shape Data

(331, 9)

Describe Data

         is_fraud
count  330.000000
mean     0.230303
std      0.421666
min      0.000000
25%      0.000000
50%      0.000000
75%      0.000000
max      1.000000

Nilai Mean =  0.23030303030303031
Persentase =  23.03 %

**Task 3 (Data Preparation / Cleaning:)**

**a** Penanganan Tipe Data & Inkonsistensi: Pastikan setiap kolom memiliki tipe data yang sesuai. Kolom waktu (timestamp) harus diubah menjadi format datetime untuk memungkinkan analisis berbasis waktu.

**b**  Penanganan Missing Values: Identifikasi kolom dengan nilai yang hilang. Berikan justifikasi yang logis untuk metode penanganan yang Anda pilih (misalnya, menghapus baris, atau mengisi dengan nilai tertentu seperti "Unknown").

**c**  Penanganan Outliers: Lakukan analisis outlier pada kolom transaction_amount. Gunakan visualisasi seperti Box Plot untuk menampilkannya. Berikan argumen apakah outlier ini perlu ditangani atau justru merupakan sinyal penting dalam kasus fraud.

**d** Penanganan Duplicated Data: Periksa apakah ada transaksi yang terduplikasi secara identik dan tentukan cara menanganinya.

**Jawaban 3**

**Task 4 (Exploratory Data Analysis (EDA):)**

**a** Buatlah minimal 5 visualisasi data yang relevan untuk membandingkan karakteristik antara transaksi fraud dan non-fraud.

**b**  Contoh analisis yang bisa dilakukan:

        * Perbandingan distribusi transaction_amount antara transaksi fraud dan non-fraud (misalnya menggunakan Histogram atau  Box Plot).
        * Analisis fraud berdasarkan waktu (misalnya, jumlah fraud per jam dalam sehari atau per hari dalam seminggu).
        * Analisis fraud berdasarkan kategori (misalnya, tipe perangkat atau lokasi).

**c**  Setiap visualisasi harus memiliki judul, label yang jelas, dan interpretasi mendalam yang menyoroti insight penting.

**Jawaban 4**

**Task 5 (Sintesis Temuan & Rekomendasi Pra-Pemodelan)**
Berdasarkan seluruh analisis EDA Anda, rangkum temuan utama dan berikan rekomendasi awal.

**a** Karakteristik Kunci Transaksi Fraud:

        * Sajikan 3 hingga 5 karakteristik paling menonjol dari transaksi yang teridentifikasi sebagai fraud. Contoh: "Transaksi fraud cenderung memiliki nilai nominal yang sangat tinggi atau sangat rendah dibandingkan transaksi normal," atau "Aktivitas fraud meningkat secara signifikan pada jam-jam dini hari."

**b**  Rekomendasi Awal:

        * Berikan rekomendasi konkret kepada tim produk atau tim Machine Learning berdasarkan temuan Anda. Rekomendasi ini bisa berupa usulan aturan sederhana atau variabel baru yang potensial.
        * Contoh Rekomendasi: "Kami merekomendasikan untuk membuat aturan penandaan (flagging) sementara untuk transaksi di atas $1000 yang terjadi antara pukul 02:00 - 05:00 pagi untuk ditinjau lebih lanjut," atau "Variabel 'waktu sejak transaksi terakhir' perlu dibuat karena fraud sering terjadi dalam rentetan transaksi berdekatan."

**c**  kesimpulan.

        * Tuliskan paragraf kesimpulan yang merangkum nilai dari analisis Anda dan bagaimana hasil ini dapat membantu "PayNow" dalam upaya memerangi penipuan.

**Jawaban 5**